{
 "title": "Azure Data Factory",
 "description": "Monitor Your ADF pipelines and activities. And Find out easily if any failures occur.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DataSource",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "Subscription", "label": "Subscription", "query": "Subscriptions()" },
   { "name": "ResourceGroupADF", "label": "Res. Group", "query": "ResourceGroups($Subscription)" },
   {
    "name": "ADF",
    "label": "ADF",
    "query": "ResourceNames($Subscription,$ResourceGroupADF, Microsoft.DataFactory/factories)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of pipelines runs in success",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Computation" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{name}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "Name", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "$$hashKey": "object:58", "text": "Failure Type", "value": "FailureType" },
       { "$$hashKey": "object:59", "text": "Pipeline", "value": "Name" }
      ],
      "metricDefinition": "Microsoft.DataFactory/factories",
      "metricName": "PipelineSucceededRuns",
      "metricNamespace": "Microsoft.DataFactory/factories",
      "resourceGroup": "$ResourceGroupADF",
      "resourceName": "$ADF",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:49", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:50", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:51", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:52", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:53", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:54", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:55", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:56", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:57", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Total Pipeline Successes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "repeat": "ADF",
   "fieldConfig": { "defaults": { "unit": "Computation" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:58", "text": "Failure Type", "value": "FailureType" },
       { "$$hashKey": "object:59", "text": "Pipeline", "value": "Name" }
      ],
      "metricDefinition": "Microsoft.DataFactory/factories",
      "metricName": "PipelineSucceededRuns",
      "metricNamespace": "Microsoft.DataFactory/factories",
      "resourceGroup": "$ResourceGroupADF",
      "resourceName": "$ADF",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:49", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:50", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:51", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:52", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:53", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:54", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:55", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:56", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:57", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Number of pipelines runs in failure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{name}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "Name", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "$$hashKey": "object:1152", "text": "Failure Type", "value": "FailureType" },
       { "$$hashKey": "object:1153", "text": "Pipeline", "value": "Name" }
      ],
      "metricDefinition": "Microsoft.DataFactory/factories",
      "metricName": "PipelineFailedRuns",
      "metricNamespace": "Microsoft.DataFactory/factories",
      "resourceGroup": "$ResourceGroupADF",
      "resourceName": "$ADF",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1143", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1144", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1145", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1146", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1147", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1148", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1149", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1150", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1151", "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Total Pipeline Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Computation" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{name}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:1152", "text": "Failure Type", "value": "FailureType" },
       { "$$hashKey": "object:1153", "text": "Pipeline", "value": "Name" }
      ],
      "metricDefinition": "Microsoft.DataFactory/factories",
      "metricName": "PipelineFailedRuns",
      "metricNamespace": "Microsoft.DataFactory/factories",
      "resourceGroup": "$ResourceGroupADF",
      "resourceName": "$ADF",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1143", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1144", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1145", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1146", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1147", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1148", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1149", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1150", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1151", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Number of activity runs in failure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{pipelinename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "Name", "filter": "", "operator": "eq" },
       { "dimension": "PipelineName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "$$hashKey": "object:402", "text": "Activity Type", "value": "ActivityType" },
       { "$$hashKey": "object:403", "text": "Pipeline", "value": "PipelineName" },
       { "$$hashKey": "object:404", "text": "Failure Type", "value": "FailureType" },
       { "$$hashKey": "object:405", "text": "Activity", "value": "Name" }
      ],
      "metricDefinition": "Microsoft.DataFactory/factories",
      "metricName": "ActivityFailedRuns",
      "metricNamespace": "Microsoft.DataFactory/factories",
      "resourceGroup": "$ResourceGroupADF",
      "resourceName": "$ADF",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:393", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:394", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:395", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:396", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:397", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:398", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:399", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:400", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:401", "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Number of activity runs in failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Computation" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": ""
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "{{pipelinename}} : {{name}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "Name", "filter": "", "operator": "eq" },
       { "dimension": "PipelineName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "$$hashKey": "object:402", "text": "Activity Type", "value": "ActivityType" },
       { "$$hashKey": "object:403", "text": "Pipeline", "value": "PipelineName" },
       { "$$hashKey": "object:404", "text": "Failure Type", "value": "FailureType" },
       { "$$hashKey": "object:405", "text": "Activity", "value": "Name" }
      ],
      "metricDefinition": "Microsoft.DataFactory/factories",
      "metricName": "ActivityFailedRuns",
      "metricNamespace": "Microsoft.DataFactory/factories",
      "resourceGroup": "$ResourceGroupADF",
      "resourceName": "$ADF",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:393", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:394", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:395", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:396", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:397", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:398", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:399", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:400", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:401", "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}